# use google/gemma-7b if you have access
base_model: google/gemma-2b-it
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: true
strict: false

bnb_config_kwargs:
  # These are default values
  llm_int8_has_fp16_weight: false
  bnb_4bit_quant_type: nf4
  bnb_4bit_use_double_quant: true

# huggingface repo
datasets:
  - path: jayshah5696/samvaad-hi-v1_gemma_format
    type: completion
    field: text
val_set_size: 0.1
dataset_prepared_path: ./LLM-data
output_dir: ./out

adapter: qlora
lora_r: 4
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

wandb_project: gemma_openhathi
wandb_run_id: model_03_qlora
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:


gradient_accumulation_steps: 2
micro_batch_size: 2
num_epochs: 1
optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: false
fp16: false
tf32: false

bfloat16: true

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 10
xformers_attention:
flash_attention: true

warmup_ratio: 0.05
evals_per_epoch: 5
eval_table_size:
# eval_max_new_tokens: 128
metric_for_best_model: "eval_loss"
saves_per_epoch: 20
save_total_limit: 20 
load_best_model_at_end: True

debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:

seed: 108